### ISSUE TITLE
There is a mistake in your NeuralUCB.ipynb.

### ISSUE THREAD

**Issue by wadx2019** [sauxpa/neural_exploration#2]
You declare the cosine function as reward_func but use h, which is a quadratic function you declared before in the Bandit initialization.  In my experiment, NeuralUCB does not work in the cosine function.

**Comment by sauxpa** [comment]
Good catch! I fixed the typo, renaming everything as "reward_func" for clarity.
Also I changed a bit the number of features to allow for an easier learning for the neural net; as you noticed, the previous problem was indeed too hard (too many features) for the neural net to learn in such small time.
